# The URL the site will be built for
base_url = "https://hyasynthesized.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "apollo"

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
analytics = false

socials = [
  { name = "bsky", url = "https://hyasynthesized.bsky.social", icon = "bluesky" },
  { name = "github", url = "https://github.com/hyasynthesized/", icon = "github" },
]

menu = [
    { name = "Home", url = "/"},
    { name = "Resume", url = "/resume"},
    { name = "AI Policy", url = "/ai"}

]